services:
  elasticsearch:
    image: baosloan/elasticsearch-ik:7.17.28
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "TZ=Asia/Shanghai"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false # 禁用安全功能(仅用于开发环境)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # 单独挂载配置文件（最安全，保留了官方的主词典）
      - ${PWD}/data:/usr/share/elasticsearch/data
      - ${PWD}/log:/usr/share/elasticsearch/logs
      - ${PWD}/ik-config/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml:ro
      - ${PWD}/ik-config/custom.dic:/usr/share/elasticsearch/config/analysis-ik/custom.dic:ro
      - ${PWD}/ik-config/stop.dic:/usr/share/elasticsearch/config/analysis-ik/stop.dic:ro
    ports:
      - "9200:9200"
    networks:
      - develop

  kibana:
    image: kibana:7.17.28
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - I18N_LOCALE=zh-CN
      - "TZ=Asia/Shanghai"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_PUBLICBASEURL=http://localhost:5601
    ports:
      - "5601:5601"
    networks:
      - develop
networks:
  develop:
    external: true