services:
  mysql:
    image: mysql:8.4.7
    container_name: mysql
    restart: always
    environment:
      LANG: C.UTF-8
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/conf:/etc/mysql/conf.d
      - ${PWD}/data:/var/lib/mysql
      - ${PWD}/log:/var/log/mysql
    networks:
      - develop

volumes:
  data:
    driver: local

networks:
  develop:
    external: true